### ISSUE TITLE
Update launch image and app icon to all sizes

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#1]
We have placeholder images, but we need to refine them and get all needed sizes.

**Comment by chrislim** [comment]
We also want to change the app icon to not have the ripple and potentially add a bit more padding between the text and the edges.

**Comment by chrislim** [comment]
One option for an app icon: a graphical dove with wings spread facing towards the user.

**Comment by LIL717** [comment]
I think these look good now.
