### ISSUE TITLE
Random crash on PersonView Note select

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#10]
Crash with message "Application tried to present a nil modal view controller on target <PersonViewController:" at random times when a note is selected in the Person View Controller

**Comment by chrislim** [comment]
I'm experiencing this too. 
These were my steps:
1. I opened the app:
2. I tapped Add new note for the first contact I got
3. I canceled (didn't create a note)
4. I swiped through some other contacts.
5. I tapped the prayer journal
6. I tapped the first note
7. I edited that note
8. I saved that note
9. I returned to the cards
10. I swiped right
11. I clicked "Add new note" for that contact
12. the program crashed.

<pre>
'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <PersonViewController: 0x12f5012d0>.'
</pre>

**Comment by chrislim** [comment]
Separate occurence:
1. Slide to first contact
2. Add new note
3. Cancel
4. Slide to second contact
5. Add new note
6. Cancel
7. Slide to third contact
8. Add new note
Crash (same as above.

**Comment by chrislim** [comment]
I think these are happening in cases where a note already exists or something. Because I just swiped through a ton of contacts, back and forth, adding notes and canceling and it never errored out.

**Comment by chrislim** [comment]
Okay it was a weird pattern: 5 contacts, the first one already had a note, the others did not.
I swiped back and forth between the first three and nothing went wrong.
When I got to the fourth and tried to add a note it crashed.

So one hypothesis is that something is leaking/crashing/problematic when one of the contacts we play with already has notes associated with it.

<pre>
'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <PersonViewController: 0x13c57e320>.'
</pre>

That code path may be getting a messed up view controller for some reason.

**Comment by chrislim** [comment]
Playing with it further it feels as if the segue vs modal situation is where the problem is happening.
I can tap on notes/add notes from person views and cancel as much as I would like.
Once I go to my prayer journal and tap on a note to edit from there and then return to trying to tap on "Add new note" from the person views, eventually one of them crashes.

**Comment by chrislim** [comment]
This was the problem I think:
<pre>
NoteViewController *noteViewController = [self.mainStoryboard instantiateViewControllerWithIdentifier:@"NoteViewController"];
</pre>

I changed it reference the storyboard directly:
<pre>
NoteViewController *noteViewController = [[UIStoryboard storyboardWithName:@"Main" bundle:nil] instantiateViewControllerWithIdentifier:@"NoteViewController"];
</pre>

The erratic crashing seems to have stopped.  see commit #5b80153ffff4
