### ISSUE TITLE
User feedback on managing too many unwanted contacts

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#104]
Many of my contacts are not ones I want included in the app: (ie things like
Domino's Pizza and State Farm insurance).  Currently, "removing" them from
Ceaseless is cumbersome if you have many of them. 

It would be nice to have a quicker way to "include" them. One suggestion is
to put the "on/off" button (like on the "Removed" page) on the main "Active"
page (You could even remove the "Removed" page).  

Another option would be to provide swipe gestures (like in the Apple email
app) so that swipe right gives two options - Favorite and Remove.
	
A third option is to provide an "Edit" button on the top left that allows
for multi-select of contacts and then an action button (Favorite, Remove,
and maybe a Select All/Deselect All) at the bottom. 

I actually want to comment that currently the "Favorite" and "Removed"
status seems a little unclear. For example, I can "Remove" a contact and
still have them as a "Favorite", which seems odd.  Maybe something a little
more simple, with "Favorite" being just a "star" that is clicked on or off,
and a swipe right to move a contact to the "Removed" status (from the
"Active" page) and a swipe left from the "Removed" page) to bring them back
to active.  And removing them would also un-Favorite them.

Sorry if I'm not very clear here. Just rethinking your UI on the fly.  :)

**Comment by LIL717** [comment]
a version of the third option implemented in commit https://github.com/ceaseless-prayer/CeaselessIOS/commit/f53e10530055e3ef1476e959610fd7289dcd6938
