### ISSUE TITLE
User is concerned that contact will be deleted from contacts

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#119]
A user is concerned that deleting a contact from Ceaseless will also remove it from her contacts on her phone.  
A couple options:
1.  When the user taps the Edit button on the People table, an alert would assure show "Contacts removed from Ceaseless will not be removed from Contacts"
2.  Change the word "Delete" that is exposed when the cell slides to the left to say "Remove" or "Remove from Ceaseless"  - this is easy.
3.  Change the idea to "Hidden".  Could still do #1, but #2 would be "Hide" and the tab at the top would be "Hidden".  This sounds more friendly and less permanent than remove.

**Comment by chrislim** [comment]
Let's do option 2 and see what the user thinks.



—

**Comment by LIL717** [comment]
Verbage changed to Remove and Add in commit https://github.com/ceaseless-prayer/CeaselessIOS/commit/f53e10530055e3ef1476e959610fd7289dcd6938
