### ISSUE TITLE
Help needs to do something

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#123]
When I click on help it doesn't do anything.   Could go to an FAQ page on the Ceaseless website or for now could bring up an email form like feedback.

**Comment by chrislim** [comment]
So we could load a web view with an FAQ and screenshots on how to do common actions.

**Comment by chrislim** [comment]
I've pushed a change that implements this, although we will want to flesh out the help documentation further.

**Comment by LIL717** [comment]
is it supposed to be going somewhere now though?

**Comment by chrislim** [comment]
It should 665add

**Comment by LIL717** [comment]
I think that there should be a way on that webpage for the user to contact us if their question was not answered.  Like at the bottom..."Don't see your question answered here?"   with an email form

**Comment by LIL717** [comment]
looks good
