### ISSUE TITLE
Add menu item "Review"

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#127]
We can add the links to the App Store before the app goes in.  The Ceaseless App id is 973610764.

We should use SKStoreProductViewController class so that we don't leave the app.

This is for Swift, but its what we need to do - super simple.

http://www.techotopia.com/index.php/Making_Store_Purchases_in_Swift_with_the_SKStoreProductViewController_Class

**Comment by chrislim** [comment]
This has been added and merged to master. However since our app isn't in the store yet, it doesn't actually work.

**Comment by LIL717** [comment]
I just tested it with the id of a live app and it worked properly.  It's slow, but that is the nature of it, like a web view. 

Lori Hill
