### ISSUE TITLE
iPhone 5s user feels like profile pictures are too big

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#128]
She has a smaller screen so the pictures/initials take up alot of space on her phone and she would prefer it smaller.

**Comment by LIL717** [comment]
![ios simulator screen shot apr 21 2015 4 28 22 pm](https://cloud.githubusercontent.com/assets/5344311/7264760/4cadacbe-e844-11e4-9f9f-f10f3d3c23ef.png)

**Comment by LIL717** [comment]
I think we leave it the way it is unless we get more feedback about that.
