### ISSUE TITLE
Some person images look too wide on the People view on the iPhone 5 in the simulator

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#133]
Some of the photos that were added to the Simulator look wider than than they should be.  
![ios simulator screen shot apr 21 2015 5 42 50 pm](https://cloud.githubusercontent.com/assets/5344311/7286451/e6f915a8-e900-11e4-8c03-de306aa37840.jpg)

Screenshots from an iPhone 5S show the following behavior.  No images are too wide, however some images do not fill the entire square, (Liz Power too narrow, Sophia Power too short) when they don't fill the entire square they look like they don't have rounded corners (because the rounding is on the square imageView,not the actual image. 
![img_2314](https://cloud.githubusercontent.com/assets/5344311/7286338/25ceddb8-e900-11e4-942c-4064f0fb4f99.jpg)
Apple appears to be avoiding this issue by using facial recognition to center the photo and aspect fill the circle.
![img_2309](https://cloud.githubusercontent.com/assets/5344311/7286335/25ada3be-e900-11e4-8796-a3df534550bb.jpg)
![img_2310](https://cloud.githubusercontent.com/assets/5344311/7286337/25ce1388-e900-11e4-9012-7dc2fe9d0d99.jpg)
![img_2312](https://cloud.githubusercontent.com/assets/5344311/7286336/25cdb622-e900-11e4-8010-a7c1c696ff2d.jpg)

**Comment by LIL717** [comment]
In looking at this closely, the photos that appeared wider in the Simulator are actually not wider, but they are shorter so they don't have rounded corners which give the appearance of being wider.

**Comment by LIL717** [comment]
Apparently Apple offers the face recognition API to us if we want to use it. 

http://stackoverflow.com/questions/9420188/uiimage-face-detection

**Comment by chrislim** [comment]
What should we do about this?

**Comment by LIL717** [comment]
For version 1, nothing, but let's leave it open because I think it would be kinda fun to play with the facial recognition for an update.

**Comment by LIL717** [comment]
changed the incoming ABImage to use Thumbnail instead of Original
