### ISSUE TITLE
search results in people view covered up by search by

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#136]
Recent contacts-view change seemed to cause this.

**Comment by LIL717** [comment]
I had thought maybe I didn't get this fixed, but it looks fixed to me now.  Still not completely happy with the light colored "bar" above the search bar that is there before the text field is active, but can't quite figure out the combination to remove that without pushing the searchbar up into the status bar when search is active.  At least its not covering up any of the results anymore.  What do you think?

**Comment by chrislim** [comment]
I think this is good, closing the issue for now.
