### ISSUE TITLE
note often truncates after one line

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#140]
3 lines should show before truncation

![ios simulator screen shot apr 28 2015 5 35 30 pm](https://cloud.githubusercontent.com/assets/5344311/7383076/9f49be0c-edcd-11e4-8114-150ed408165e.png)
M

**Comment by LIL717** [comment]
this actually might have more to do with the simulator than iPhone 5, need to test varying lengths of notes on an actual iPhone 5

**Comment by LIL717** [comment]
not a show stopper

**Comment by LIL717** [comment]
this is fixed in commit https://github.com/ceaseless-prayer/CeaselessIOS/commit/3a70bbaa0ca12f7f16a235bdcd37cfa67f3236a3

**Comment by chrislim** [comment]
Do I need to upload a new build?

**Comment by LIL717** [comment]
No, let's just start a next version update.   It's not ideal, but it will be ok, doesn't seem worth pushing out the date further

Lori Hill

**Comment by nylim11** [comment]
I believe this was pushed out, don't see it happening on my phone
