### ISSUE TITLE
The counts on the progress screen are not always accurate

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#141]
This is on a first load.   Should be 5/677.  Also, there does not appear to be a background image being blurred on this progress card.

![img_7347](https://cloud.githubusercontent.com/assets/5344311/7383096/ed5613f2-edcd-11e4-8f86-127381f1ab3e.PNG)

This is in the simulator  There are 12 active and 7 removed contacts in the Ceaseless Contacts.

![ios simulator screen shot apr 28 2015 5 46 44 pm](https://cloud.githubusercontent.com/assets/5344311/7383133/a751a6c2-edce-11e4-8e98-0a97e1abfb39.png)

**Comment by chrislim** [comment]
A few fixes in this commit: a8f7b42
We set the date of the cycle start to an hour before the current date so that the 3 selected on the initial run are counted as part of the progress count.

**Comment by chrislim** [comment]
Should be resolved.
