### ISSUE TITLE
Loading the note view is slow the first time

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#17]
Whether you reach it through "Add new note" or the prayer journal or something else, it takes several seconds to load which is a poor user experience. However, when I ran a profiled build it actually loaded quickly. The main build though remains slow.

**Comment by LIL717** [comment]
I am still seeing this from the person notes, but not experiencing it from the prayer journal

**Comment by chrislim** [comment]
In the prayer journal things seem fast, but person notes is still slow.

**Comment by LIL717** [comment]
commit https://github.com/ceaseless-prayer/CeaselessIOS/commit/6e4c7d6451902ed8bbe5fa32acd21e3e5eb01f17 changes transition from modal to push

**Comment by LIL717** [comment]
there is still a slight bug in the transition, but loading is much faster.
