### ISSUE TITLE
I want to turn off notifications from the settings menu

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#180]
A user wanted to do this and ended up having to go to the iOS settings to do it. We should have the option in the app.

**Comment by calvinf** [comment]
I don't think it's possible to disable notifications from the app.

http://stackoverflow.com/a/10493999

Every use case I've seen for this has involved an app giving instructions about how to open iOS notification settings for the app.

**Comment by chrislim** [comment]
Ok, I'll see. But I can within the app disable the daily reminder I think
via a setting.

**Comment by chrislim** [comment]
Closed in favor of #207
