### ISSUE TITLE
7 crashes in last 2 weeks on CFRelease of phoneNumbers?

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#204]
Got 7 crashes on this code:
https://github.com/ceaseless-prayer/CeaselessIOS/blob/master/Ceaseless/CeaselessLocalContacts.m#L484

![image](https://cloud.githubusercontent.com/assets/469630/26380544/0e4ba478-3fd4-11e7-8bfe-7dd5a6076380.png)

**Comment by LIL717** [comment]
https://developer.apple.com/reference/corefoundation/1521153-cfrelease

"If cf is NULL, this will cause a runtime error and your application will crash."

Probably need to check if phoneNumbers is NULL.

**Comment by chrislim** [comment]
Waiting for app review, but this commit should fix it: 1220ff9
