### ISSUE TITLE
add ceaslessiOS to crowdin

### ISSUE THREAD

**Issue by joejoe2016** [ceaseless-prayer/CeaselessIOS#216]
Hi,
it would be good to have ceaseless-ios also on crowdin.
What is a bit of a problem for me is that I don't have a Mac to build and test the iOS-app. (here VisualStudio AppCenter might help here, see issue #113 on the CeaslessAndroid-project.

**Comment by chrislim** [comment]
Requesting the approval from crowdin now.

**Comment by chrislim** [comment]
A project has been created here: https://crowdin.com/project/ceaselessios

**Comment by joejoe2016** [comment]
Thanks
