### ISSUE TITLE
OS X and XCode in Virtual Machine

### ISSUE THREAD

**Issue by joejoe2016** [ceaseless-prayer/CeaselessIOS#218]
Hi,
as I don't have a Mac with OS X (which is necessary to build and iOS-app) I'm thinking about the option of using OS X and XCode in a Virtual Machine with ubuntu/Microsoft as host system.
I saw online OS X 10.6 (which seems to be the last version that is shipped with a DVD/iso) for around $18.
Any experience with this topic?
Greetings
joejoe2016

**Comment by calvinf** [comment]
I don’t believe it’s possible to run any normal version of macOS in a
virtualized environment and that specific version is too old to run
relevant versions of Xcode.

**Comment by joejoe2016** [comment]
Hi calvinf,
yes, you're probably right. Apart from that it's not allowed by the EULA to use as the host of a virtualization system another OS that is not Mac.
There are some solutions around that bring Mac OS to the cloud, but they are paid (between $15 and $30 dollars a month).
I checked the prices use used Mac minis and I think in order to get one that is not too old it's necessary to spend at least around $500 bugs.

**Comment by calvinf** [comment]
Yes even used Macs cost a bit. Potentially you can get some kind of a used
MacBook from 2014 to 2016 that can run Mojave but as you’ve noted they’re
not cheap.

**Comment by joejoe2016** [comment]
I heard about the following ideas that I'd like to mention here for completeness:
- https://saintlad.com/install-macos-sierra-in-virtualbox-on-windows-10/
- install https://hackintosh.com/ on an older laptop
- search the web for a used mac mini:
https://www.iused.nl/256-tweedehands-refurbished-apple-macmini?gclid=EAIaIQobChMI85q_uvj23QIVlobVCh20PQ_0EAAYAiAAEgLmqfD_BwE
