### ISSUE TITLE
tapping on the note row doesn't go to the note detail

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#37]
On the person view notes, you have to touch the text itself to get to the details, but the user would probably just tap on the row expecting to see the details.

**Comment by LIL717** [comment]
I think this is actually the same as issue #17

**Comment by chrislim** [comment]
Sounds like this is solved through the navigation controller method.

**Comment by LIL717** [comment]
I am never seeing this happen
