### ISSUE TITLE
Prayer Journal button and Share Scripture button are not white

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#44]
the tint needs to be changed for these buttons (or the default tint needs to be changed so they will pick them up)   This was fixed previously but somehow the changes were lost.

**Comment by chrislim** [comment]
Hmm, they are still showing up white on mine...are you building from master?

**Comment by LIL717** [comment]
commit https://github.com/ceaseless-prayer/CeaselessIOS/commit/dfc200ab9731d6a2871f5cef548fd8b0424ac2de fixes this
