### ISSUE TITLE
People table "jittery" when contacts are syncing

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#45]
the experience might be better the user just gets a message "Syncing contacts with address book, please try again" until the syncing process is complete.

**Comment by chrislim** [comment]
Interesting, why does that happen if the contacts syncing is supposedly
happening on a background thread?

**Comment by LIL717** [comment]
I think because it is not blocking, and the fetchedResultsController is listening for changes to the data, so it is flipping out trying to keep the table in sync.   When I set a breakpoint in the controllerDidChangeContent method, it was hitting there over and over again.  Could we fire off a notification when syncing starts and check for that when the contactListViewController is going to load and just show an alert from the menu, then turn it off when syncing is done.

**Comment by LIL717** [comment]
commit https://github.com/ceaseless-prayer/CeaselessIOS/commit/17f8a39cb300694280ea15ff5b1f683549749373 fixes this by checking the "syncing" bool on the ceaselessLocalContacts class
