### ISSUE TITLE
We should track in-app usage

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#47]
We may want to integrate Google analytics into the app.https://developers.google.com/analytics/devguides/collection/ios/v3/

**Comment by LIL717** [comment]
People also use Flurry for this https://developer.yahoo.com/analytics/

**Comment by chrislim** [comment]
I looked into flurry, but since I already have a google analytics account setup for Ceaseless web, I decided to use the Google library for now. Working on integration now.

**Comment by chrislim** [comment]
a1bd7adb4303f65742e1f14fac7e356b4da1435d integrates the google analytics.

**Comment by chrislim** [comment]
Tentative list of metrics:
* app load
* view root
* view prayer journal
* view note
* add note
* count of people prayed for out of total
* count of people favorited
* count of people removed
* time spent in app
* time spent on each card
* address book synced
* invite sent
* friend contacted through app

**Comment by chrislim** [comment]
These metrics should now be available.
