### ISSUE TITLE
Search Prayer Journal by name

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#60]
It would be nice to search the prayer journal by name as well as text.  That cannot happen without a lot of work because the names are an ordered set on the note, thus a predicate cannot be formed for the searchFetchedResultsController

It is possible to see all the notes for a person by selecting them in the People table.

:(

**Comment by chrislim** [comment]
We could deal with this via a toggle to search for name vs search for textual content.

**Comment by LIL717** [comment]
fixed in commit https://github.com/ceaseless-prayer/CeaselessIOS/commit/db3cdcd50393f8c27a58f4ad337449b3e8e1dddd
