### ISSUE TITLE
Replace all abort() s with proper error handling

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#62]
abort crashes the app, which many times is not what we want to do. we need to comb the codebase and deal with those cases as appropriate.

**Comment by chrislim** [comment]
Maybe we don't need to worry about this yet?
http://stackoverflow.com/questions/2262704/iphone-core-data-production-error-handling

**Comment by LIL717** [comment]
Marcus Zarra is like the King of Core Data - so if he says let it crash, then I'm with him :)
