### ISSUE TITLE
Constraint conflict on People Table

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#70]
When the People list is being built, the following constraint warning is happening:

2015-04-10 13:38:22.700 Ceaseless[438:51155] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x17508f5f0 V:[UILabel:0x12ef9ef60(41)]>",
    "<NSLayoutConstraint:0x175092610 V:[UILabel:0x12ef9ef60]-(1)-|   (Names: '|':UITableViewCellContentView:0x17419b790 )>",
    "<NSLayoutConstraint:0x1750920c0 V:|-(1)-[UILabel:0x12ef9ef60]   (Names: '|':UITableViewCellContentView:0x17419b790 )>",
    "<NSLayoutConstraint:0x171086310 'UIView-Encapsulated-Layout-Height' V:[UITableViewCellContentView:0x17419b790(43.5)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x17508f5f0 V:[UILabel:0x12ef9ef60(41)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by LIL717** [comment]
fixed in commit https://github.com/ceaseless-prayer/CeaselessIOS/commit/919a864dca89fac96149eb1ce9332288a6ba8056

**Comment by LIL717** [comment]
the change to hard code the width to 41 for the iPad is causing the constraint conflict warning on the iPhone again

**Comment by chrislim** [comment]
Yea, I added back the 41 width constraint because on my ipad all the images were of varying sizes without it...what is the right way?

**Comment by LIL717** [comment]
I will work on it... and test on both iPad and iPhone :)

**Comment by LIL717** [comment]
think its fixed now with commit https://github.com/ceaseless-prayer/CeaselessIOS/commit/4fe5e7f3dccfaae5f2a3ff2bc0459a7421f4dea5
