### ISSUE TITLE
System message on progress page needs fit all screens

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#74]
The message truncates both right a left on smaller screen.  Need to set constraints on leading and trailing.

**Comment by chrislim** [comment]
![image](https://cloud.githubusercontent.com/assets/469630/7103536/a483e994-e060-11e4-9e40-9c6493741c77.png)

**Comment by LIL717** [comment]
fixed in commit 29d5bafc2e93f00c4be472fc9185de1774b7d850
