### ISSUE TITLE
Notes field on Add Notes view is hidden by keyboard

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#76]
It needs to scroll instead of letting text disappear underneath the keyboard

**Comment by chrislim** [comment]
I recently committed a change that made the keyboard not appear unless the user is editing the note, but it does need to scroll when editing.

**Comment by chrislim** [comment]
So I just created a long note on my iPad and it looks like it does scroll...but only when it reaches the very very bottom of the field--so if the field resized when the keyboard appears, it probably would scroll as desired.

Secondly, i noticed that when the note is long, there is a scrollbar on the right, but it is dark--if we made it white like the font it would be more visible.

**Comment by LIL717** [comment]
I saw the change to make the textField the first responder, I left it that way.

fixed in https://github.com/ceaseless-prayer/CeaselessIOS/commit/bd824ce66309a3a4fbf824ef5cb88a4c4918b9ad

I think we should leave the scroll indicator as it is,  iOS users are used to it being very unobtrusive.
