### ISSUE TITLE
First install of app only loaded self

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#77]
One of our beta testers reported that she downloaded the app, gave permission for access to contacts, but only got herself to pray for and had no other contacts in People.    When she deleted the app and reinstalled it, all of her contacts were loaded

**Comment by chrislim** [comment]
Do you think this has to do with some misordering of initializing contacts and getting address book permissions? We probably need to test that path more and more of starting the app without address book access and seeing where it crashes.

**Comment by LIL717** [comment]
I debugged this a bit on my husband's phone.  We are requesting access to the address book in the PersonPicker class, but the methods to get the records from AddressBook get kicked off before that in CeaselessLocalContacts.  The reason that self works is that there is an AB access request in that process.  I confirmed this by adding a note.   The NoteViewController also has an AB access request so the person who was tagged in the note shows up in the People list.  The alert view for the user to give access to Contacts does eventually get shown, but too late.   

If the user deletes the app after they gave permission, all the contacts are showing when they reinstall.

Its tough to test this because once the setting for Contacts is turned ON, it stays on even if the app is deleted and the phone is restarted.  I found this: 
http://stackoverflow.com/questions/12596165/is-it-possible-to-reset-the-privacy-settings-in-ios
At the end of this post it mentions a sequence to delete, restart and then manually set the date of the device ahead by 2 days to be able to force the settings to be forgotten, but you have to do it for each build - an incentive to get it right the first time :)

Probably related to this misordering of permission and initializing - 
when the address book access is turned off in Settings and the app is deleted from the device.  When the app is reinstalled it crashes on this line:
    for (CFIndex i = 0; i < CFArrayGetCount(records); i++)
in methods - (NSArray *)getUnifiedAddressBookRecords:(ABAddressBookRef)addressBook {
in class CeaselessLocalContacts

**Comment by chrislim** [comment]
Should this one be resolved given our recent change?

**Comment by LIL717** [comment]
Yes!

Lori Hill
