### ISSUE TITLE
App doesn't stay on the people view when I background it and return

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#80]
When i am in the people view, when i background the app and return, why does it not stay, but rather go to the daily experience?

**Comment by LIL717** [comment]
I just spent some time trying to research this.  I thought it might be related to showing and hiding the Loading label and listening for applicationDidBecomeActive:  but that does not seem to be the case.

I was thinking that perhaps it had something to do with the Menu (and its children, People and Settings, which both dismiss when the app becomes active) being presented Modally.  And that holds true, except that if the Add Notes view has been segued to from the Person View in the Daily Experience, that view also gets dismissed when the app becomes active.  However, the Prayer Journal does not behave this way AND the Add Notes view does not get dismissed if it was segued to via the Prayer Journal.

**Comment by chrislim** [comment]
One thing I also just fixed in:
0960c89de5bad903f2a05da227a52f2ad552c192

My comparison of number of midnights was wrong so that even when not in developer mode it was refreshing because it was comparing an NSNumber with an int. The fix doesn't solve this ticket, but could have contributed to some problems which is why I'm mentioning it.

**Comment by LIL717** [comment]
try switching to use navigation controller instead of modal

**Comment by LIL717** [comment]
fixed  in commit https://github.com/ceaseless-prayer/CeaselessIOS/commit/fee703071295a789646f41c910bbd40b2e50673f by changing navigation control from modal to push
