### ISSUE TITLE
Tapping on the ... "More" button is kind of tricky

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#81]
As a user on the iPhone 5s, it was tough to touch the ... more button on the person card. If we could make it a bigger target that would be better.

**Comment by chrislim** [comment]
related to #73

**Comment by LIL717** [comment]
it is the same size as icons in the nav bar 44 x 44
now that it isn't getting pushed off  by long names it should be fine
commit https://github.com/ceaseless-prayer/CeaselessIOS/commit/dfb68963f09ae3470fc7344c485949842d6e588b
