### ISSUE TITLE
See a person view from the note view?

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#82]
When I open a note and tap twice on a tagged person I expect it to take me to the details about that person.
If I want to remove a tagged person, I expect to tap once and then press delete.

**Comment by LIL717** [comment]
add gesture recognizer for double tap to segue to person view

**Comment by LIL717** [comment]
Ack - the person view that is presented this way needs to be pushed down 64 bytes, the name bar is hidden under the nav bar

**Comment by LIL717** [comment]
its correct now after all the nav bar changes in https://github.com/ceaseless-prayer/CeaselessIOS/commit/9425d28244ca812a76bf74dd2a8b396db41c0a33
