### ISSUE TITLE
Person card note view heights/profile picture size should be more consistent

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#84]
Compare these two examples:
![sl_card_1](https://cloud.githubusercontent.com/assets/469630/7103547/1e7f97ac-e061-11e4-8ba9-06f0b5d4c25e.png)
![mc_card_1](https://cloud.githubusercontent.com/assets/469630/7103548/200c16b8-e061-11e4-86b9-e86fb398c368.png)

**Comment by LIL717** [comment]
fixed in commit https://github.com/ceaseless-prayer/CeaselessIOS/commit/dfb68963f09ae3470fc7344c485949842d6e588b
