### ISSUE TITLE
Create a credits/legal page in the menu

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#89]
This is where we can thank people, acknowledge the Digital Bible Platform we're using, etc.

**Comment by chrislim** [comment]
We may need to add legal verbiage here too if we depend on any code that requires a license to be shown to the end user.

**Comment by chrislim** [comment]
Using: https://developer.apple.com/library/ios/documentation/AddressBook/Reference/ABPersonRef_iPhoneOS/#//apple_ref/c/func/ABAddressBookCopyArrayOfAllPeopleInSource

We can only fetch local contacts and thereby ignore ones from exchange. 

https://developer.apple.com/library/prerelease/ios/documentation/AddressBook/Reference/ABSourceRef_iPhoneOS/index.html#//apple_ref/doc/constant_group/Source_Types

This didn't cause any reduction of contacts on my iPad, so other app seem to sync contacts to the local book. Exchange is the main one that seems to have its own special source in addition to LDAP and other organizational systems.

**Comment by chrislim** [comment]
Should we have a donate thing as well?

**Comment by chrislim** [comment]
We should have buttons that takes people to the Facebook page, the Twitter page and a contact us page.

Some things to acknowledge:
* We may need to show the Apache 2 license because of some code
* We may need to acknowledge font awesome
* We can show the MIT license
* We should show a list of contributors, though we don't need to mention their roles.
* Contributors of images
* Digital Bible Platform/server capacity

**Comment by chrislim** [comment]
The first pass of this information is done.
http://www.ceaselessprayer.com/ios_about.html
I need to know the name of the person who provided some of the photos.

**Comment by LIL717** [comment]
Karin Kaczmarowski


Lori Hill

**Comment by LIL717** [comment]
looks good
