### ISSUE TITLE
Confusing when note is not shown since I did not tag anyone

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#97]
I created two notes where no one was tagged and they did not show up in the view.
I think this is because the default is to show Friends instead of Me.
This really confused me because I thought the note did not get created.

**Comment by LIL717** [comment]
maybe untagged notes should just automatically get tagged with the user if there is no tag.  With the search capabililty in Notes, they could just search on themself to find their own notes and we could eliminate the tabs for Friends and Me.

**Comment by chrislim** [comment]
Yea I've been thinking about option 2.

**Comment by LIL717** [comment]
Friends and Me segmented control removed in commit https://github.com/ceaseless-prayer/CeaselessIOS/commit/10963ea0aeb03183d9a303809bcc2263fef40717
